Mappings:
  EC2MAPPING:
    us-east-1:
      MyAMI1: ami-0f88e80871fd81e91
    us-west-1:
      MyAMI1: ami-04fc83311a8d478df
    us-east-2:
      MyAMI1: ami-058a8a5ab36292159
Resources:
   myInstance:
     Type: 'AWS::EC2::Instance'
     Properties: 
        ImageId: !FindInMap [ EC2MAPPING, "us-east-1", MyAMI1 ]
        InstanceType: t2.micro
